remote_theme: slatedocs/slate
title: Learning CUDA programming to run on structured curvilinear meshes
description: Learning CUDA programming to run on structured curvilinear meshes
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  repository_url: https://github.com/gantech/struct_grid
