remote_theme: slatedocs/slate
title: StructGridCUDA Documentation
description: Documentation for the StructGridCUDA computational fluid dynamics framework
baseurl: "/struct_grid" # the subpath of your site
url: "https://gantech.github.io" # GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
# Additional settings
sass:
  style: compressed

# Extra styles
extra_css:
  - stylesheets/custom.css
